<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
?>
<div class="head-quote">
    <div class="card-quote-text color-grey-9c"><?php echo __('For large quantity and custom order please feel free to');?></div>
    <div class="card-quote-link">
        <a href="<?php echo $this->getUrl('contact-form');?>">
            <span class="text"><?php echo __('send us enquiry');?></span>
        </a>
    </div>
</div>