<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper(\Magento\Search\Helper\Data::class);
?>
<div class="card-search-bar">
    <div class="card-wrapper">
        <form id="search_mini_form" action="<?= $block->escapeUrl($helper->getResultUrl()) ?>" method="get">
            <div class="card-row">
                <div class="card-input-box">
                    <input id="search"
                           data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?= $block->escapeUrl($helper->getSuggestUrl())?>",
                                "destinationSelector":"#search_autocomplete",
                                "minSearchLength":"<?= $block->escapeHtml($helper->getMinQueryLength()) ?>"}
                           }'
                           type="text"
                           name="<?= $block->escapeHtmlAttr($helper->getQueryParamName()) ?>"
                           value="<?= $block->escapeHtmlAttr($helper->getEscapedQueryText()) ?>"
                           placeholder="<?= $block->escapeHtmlAttr(__('What are you looking for…')) ?>"
                           maxlength="<?= $block->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"
                           aria-expanded="false"/>
                    <?php /*<div id="search_autocomplete" class="search-autocomplete"></div>*/?>
                    <?= $block->getChildHtml() ?>
                    
                    <button type="submit" class="button-search" title="<?= $block->escapeHtmlAttr(__('SEARCH')) ?>" aria-label="Search">
                        <span class="d-none d-lg-inline"><?= $block->escapeHtmlAttr(__('SEARCH')) ?></span><i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
