<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */ ?>
<?php $_item = $block->getItem();?>
<?php $_order = $block->getItem()->getOrderItem()->getOrder();
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();  
$product = $objectManager->create('Magento\Catalog\Model\Product')->load($_item->getProductId()); 
$productUrl = $product->getProductUrl();
if($product->getTypeId() == 'configurable') {
    $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();   
    $configurable = $objectManager->get('\Magento\ConfigurableProduct\Model\Product\Type\Configurable');
    $superAttribute = array();
    foreach ($block->getItemOptions() as $option) {
        $superAttribute[$option['option_id']] = $option['option_value'];
    }
    $product = $configurable->getProductByAttributes($superAttribute ,$product);
}?>
<tr id="order-item-row-<?= (int) $_item->getId() ?>">
    <td class="col detail" data-th="<?= $block->escapeHtmlAttr(__('Product Name')) ?>">
        <div class="product-item-details">
            <strong class="product-item-name">
                <a href="<?= $block->escapeHtml($productUrl) ?>"><?= $block->escapeHtml($product->getName()) ?></a>
            </strong>
            <?php if ($_options = $block->getItemOptions()) : ?>
                <dl class="product options list">
                    <?php foreach ($_options as $_option) : ?>
                        <span><?= $block->escapeHtml($_option['label']) ?> = </span>
                        <?php if (!$block->getPrintStatus()) : ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <span>
                                <?php if (isset($_formatedOptionValue['full_view'])) : ?>
                                    <?= $block->escapeHtml($_formatedOptionValue['full_view'], ['a']) ?>
                                <?php else : ?>
                                    <?=$block->escapeHtml($_formatedOptionValue['value'], ['a']) ?>
                                <?php endif; ?>
                            </span>
                        <?php else : ?>
                            <span>
                                <?= /* @noEscape */ nl2br($block->escapeHtml($_option['print_value'] ?? $_option['value'])) ?>
                            </span>
                        <?php endif; ?><br>
                    <?php endforeach; ?>
                </dl>   
            <?php endif; ?> 
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock) :?>
                <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
            <?php endif; ?>
            <?= $block->escapeHtml($_item->getDescription()) ?>                                        
        </div>
    </td>
    <td class="col sku" data-th="<?= $block->escapeHtmlAttr(__('Part Number')) ?>"><?= /* @noEscape */ $product->getData('part_number') ?></td>
    <td class="col price" data-th="<?= $block->escapeHtmlAttr(__('Price')) ?>">
        <?= $block->getItemPriceHtml() ?>
    </td>
    <td class="col qty" data-th="<?= $block->escapeHtmlAttr(__('Qty Invoiced')) ?>">
        <span class="qty summary"><?= (float) $_item->getQty() ?></span>
    </td>
    <td class="col subtotal" data-th="<?= $block->escapeHtmlAttr(__('Subtotal')) ?>">
        <?= $block->getItemRowTotalHtml() ?>
    </td>
</tr>
