<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/**  @var $block \Magento\Checkout\Block\Cart */
?>
<?php if ($block->getContinueShoppingUrl()) :?>
    <a class="action continue"
       href="<?= $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
       title="<?= $block->escapeHtmlAttr(__('Continue Shopping')) ?>">
        <span><?= $block->escapeHtml(__('Continue Shopping')) ?></span>
    </a>
<?php endif; ?>