<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<div class="row">
    <div class="col-md-5">
        <h1 class="mb-md-5 pb-md-4 mb-3"><?= $block->escapeHtml(__('Forgot Your Password')) ?></h1>
        <div class="card-image d-none d-md-block"><img src="<?php echo $this->getViewFileUrl('images/banner/nut2.jpg'); ?>" alt=""></div>
    </div>
    <div class="col-md-6">
        <form class="form password forget"
            action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
            method="post"
            id="form-validate"
            data-mage-init='{"validation":{}}'>
            <div class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                <div class="field field-wide note"><?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')) ?></div>
                <div class="field field-wide email required">
                    <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input type="email" name="email" alt="email" id="email_address" class="input-text" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
            </div>
            <div class="actions-button">
                <div class="my-4">
                    <button type="submit" class="Create an Account" title="<?= $block->escapeHtmlAttr(__('Reset My Password')) ?>"><span><?= $block->escapeHtml(__('Reset My Password')) ?></span></button>
                </div>
                <div class="text-center"><p><?= $block->escapeHtmlAttr(__('Already have an account?')) ?><br>
                <a class="small-title color-orange forget-pass classic-link-hover register-link" href="<?= $block->escapeHtmlAttr($this->getUrl('customer/account/login')) ?>"><?= $block->escapeHtml(__('Login')) ?></a></p></div>
            </div>
        </form>
    </div>
</div>
