<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\Resetpassword $block */
?>
<div class="row">
    <div class="col-md-5">
        <h1 class="mb-md-5 pb-md-4 mb-3"><?= $block->escapeHtml(__('Set a New Password')) ?></h1>
        <div class="card-image d-none d-md-block"><img src="<?php echo $this->getViewFileUrl('images/banner/nut1.jpg'); ?>" alt=""></div>
    </div>
    <div class="col-md-6">
        <form action="<?= $block->escapeUrl($block->getUrl('*/*/resetpasswordpost', ['_query' => ['token' => $block->getResetPasswordLinkToken()]])) ?>"
            method="post"
                <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?>
            id="form-validate"
            class="form password reset"
            data-mage-init='{"validation":{}}'>
            <div class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                <div class="field field-wide password required" data-mage-init='{"passwordStrengthIndicator": {}}'>
                    <label class="label" for="password"><span><?= $block->escapeHtml(__('New Password')) ?></span></label>
                    <div class="control">
                        <input type="password" class="input-text" name="password" id="password"
                            data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                            data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                            data-validate="{required:true, 'validate-customer-password':true}"
                            autocomplete="off">
                        <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                            <div id="password-strength-meter" class="password-strength-meter">
                                <?= $block->escapeHtml(__('Password Strength')) ?>:
                                <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                                    <?= $block->escapeHtml(__('No Password')) ?>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="field field-wide confirmation required">
                    <label class="label" for="password-confirmation"><span><?= $block->escapeHtml(__('Confirm New Password')) ?></span></label>
                    <div class="control">
                        <input type="password" class="input-text" name="password_confirmation" id="password-confirmation" data-validate="{required:true,equalTo:'#password'}" autocomplete="off">
                    </div>
                </div>
            </div>
            <div class="actions-button">
                <div class="my-4">
                    <button type="submit" title="<?= $block->escapeHtmlAttr(__('Set a New Password')) ?>"><span><?= $block->escapeHtml(__('Set a New Password')) ?></span></button>
                </div>
                <div class="text-center"><p><?= $block->escapeHtmlAttr(__('Already have an account?')) ?><br>
                <a class="small-title color-orange forget-pass classic-link-hover register-link" href="<?= $block->escapeHtmlAttr($this->getUrl('customer/account/login')) ?>"><?= $block->escapeHtml(__('Login')) ?></a></p></div>
            </div>
        </form>
    </div>
</div>
