<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
/** @var \Kos\QuoteCart\Helper\Data $helperKos */
$helperKos = $this->helper(Kos\QuoteCart\Helper\Data::class);
?>
<?php
if($product->getTypeId() == 'configurable') {
    $product = $helperKos->getChildProduct($this->getItem());
}
$dayToShip = $helperKos->getDaytoShip($product,$block->getQty());

?>
<tr class="item-info">
    <td data-th="<?php echo $block->escapeHtml(__('Image')); ?>" class="col item col-image">
        <span class="product-item-photo"><?php echo $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml(); ?></span>
    </td>
    <td class="col" data-th="<?php echo $block->escapeHtml(__('Part Number')); ?>">
        <?= $block->escapeHtml($product->getData('part_number')); ?>
    </td>
    <td data-th="<?= $block->escapeHtmlAttr(__('Name')) ?>" class="col name">
        <div class="product-item-details">
            <strong class="product-item-name">
                <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
                   title="<?= $block->escapeHtmlAttr($block->getProductName()) ?>"
                   tabindex="-1"
                   class="product-item-photo">
                    <?= $block->escapeHtml($product->getName()) ?>
                </a>
            </strong>
            <?php if ($messages = $block->getMessages()) :?>
                <?php foreach ($messages as $message) :?>
                    <div class= "cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                        <div><?= $block->escapeHtml($message['text']) ?></div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock) :?>
                <?= $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif;?>
        </div>
    </td>
    <td class="col" data-th="<?php echo $block->escapeHtml(__('Material')); ?>">
        <?= $block->escapeHtml($product->getAttributeText('material')); ?>
    </td>
    <td class="col" data-th="<?php echo $block->escapeHtml(__('Plating')); ?>">
        <?= $block->escapeHtml($product->getAttributeText('plating')); ?>
    </td>
    <td class="col" data-th="<?php echo $block->escapeHtml(__('Diameter')); ?>">
        <?= $block->escapeHtml($product->getAttributeText('diameter')); ?>
    </td>
    <td class="col" data-th="<?php echo $block->escapeHtml(__('Length')); ?>">
        <?= $block->escapeHtml($product->getAttributeText('length')); ?>
    </td>
    <?php if ($canApplyMsrp) :?>
        <td class="col msrp" data-th="<?= $block->escapeHtmlAttr(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= $block->escapeHtml(__('See price before order confirmation.')) ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map"
                       id="<?= ($block->escapeHtmlAttr($helpLinkId)) ?>"
                       data-mage-init='{"addToCart":{
                                            "helpLinkId": "#<?= $block->escapeJs($block->escapeHtml($helpLinkId)) ?>",
                                            "productName": "<?= $block->escapeJs($block->escapeHtml($product->getName())) ?>",
                                            "showAddToCart": false
                                            }
                                        }'
                    >
                        <span><?= $block->escapeHtml(__("What's this?")) ?></span>
                    </a>
                </span>
        </td>
    <?php else :?>
        <td class="col" data-th="<?php echo $block->escapeHtml(__('Unit price')); ?>">
            <?= $block->getUnitPriceHtml($_item); ?>
        </td>
    <?php endif; ?>
    <td class="col" data-th="<?php echo $block->escapeHtml(__('Days to Ship')); ?>">
        <?= $block->escapeHtml($dayToShip); ?>
    </td>
    <td class="col qty box-tocart col-qty" data-th="<?= $block->escapeHtmlAttr(__('QTY')) ?>">
        <div class="field qty">
            <label for="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty">
                <span class="label"><?= $block->escapeHtml(__('QTY')) ?></span>
            </label>
            <div class="control qty">
                <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                       name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                       data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                       value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                       type="number"
                       size="4"
                       step="any"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="{required:true,'validate-greater-than-zero':true}"
                       data-role="cart-item-qty"/>
                <button type="submit" name="update_quote_action"
                        value="update_qty"
                        title="<?php echo $block->escapeHtml(__('Update')); ?>"
                        class="action update"
                        id="update_quote_button-<?= $_item->getId(); ?>">
                    <span><?php echo __('Update'); ?></span>
                </button>
                <div class="qty-changer">
                    <a href="javascript:void(0)" class="qty-inc"><span class="hs-icon-up-dir"></span></a>
                    <a href="javascript:void(0)" class="qty-dec"><span class="hs-icon-down-dir"></span></a>
                </div>
            </div>
        </div>
    </td>

    <td class="col subtotal" data-th="<?= $block->escapeHtmlAttr(__('Total Price')) ?>">
        <?php if ($canApplyMsrp) :?>
            <span class="cart msrp subtotal">--</span>
        <?php else :?>
            <?= $block->getRowTotalHtml($_item) ?>
        <?php endif; ?>
    </td>
    <td class="col col-actions">
        <div class="actions-toolbar">
            <?= /* @noEscape */ $block->getActions($_item) ?>
        </div>
    </td>
</tr>
<script type="text/x-magento-init">
    {
        ".item-info": {
            "Magento_Theme/js/component/qty-changer": {}
        }
    }
</script>
