<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Contact\Block\ContactForm $block */
?>
<div class="row mb-md-5 pb-4">
    <div class="col-lg-5">
        <h1><?= $block->escapeHtml('Contact Form') ?></h1>
    </div>
    <div class="col-lg-6">
        <p><?= $block->escapeHtml('Let\'s get in touch! Send us your enquiry and we will get back to you as soon as possible.') ?></p>
    </div>
</div>
<div class="row">
    <div class="col-md-5 mb-4 mb-md-0 d-none d-lg-block">
        <?php 
        echo $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('contact-form-image')
        ->toHtml();
        ?>
    </div>
    <div class="col-lg-6 col-form">
        <form class="contact-form"
            action="<?= $block->escapeUrl($block->getFormAction()) ?>"
            id="contact-form"
            method="post"
            data-hasrequired="<?= $block->escapeHtmlAttr('* Required Fields') ?>"
            data-mage-init='{"validation":{}}'>
            <div class="row fields">
                <div class="col-md-12 field">
                    <label class="label" for="name"><span><?= $block->escapeHtml('Name') ?></span></label>
                    <div class="control">
                        <input name="name" id="name" title="<?= $block->escapeHtmlAttr('Name') ?>" value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('name') ?: $this->helper(\Magento\Contact\Helper\Data::class)->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
                    </div>
                </div>
                <div class="col-md-6 field">
                    <label class="label" for="email"><span><?= $block->escapeHtml('Email Address') ?></span></label>
                    <div class="control">
                        <input name="email" id="email" title="<?= $block->escapeHtmlAttr('Email Address') ?>" value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('email') ?: $this->helper(\Magento\Contact\Helper\Data::class)->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                    </div>
                </div>
                <div class="col-md-6 field">
                    <label class="label" for="telephone"><span><?= $block->escapeHtml('Phone Number') ?><em><?= $block->escapeHtml('(Optional)') ?></em></span></label>
                    <div class="control">
                        <input name="telephone" id="telephone" title="<?= $block->escapeHtmlAttr('Phone Number') ?>" value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('telephone')) ?>" class="input-text" type="text" />
                    </div>
                </div>
                <div class="col-md-12 field">
                    <label class="label" for="subject"><span><?= $block->escapeHtml('Subject') ?></span></label>
                    <div class="control">
                        <input name="subject" id="subject" title="<?= $block->escapeHtmlAttr('Subject') ?>" value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('subject')) ?>" class="input-text" type="text" data-validate="{required:true}"/>
                    </div>
                </div>
                <div class="col-md-12 field">
                    <label class="label" for="comment"><span><?= $block->escapeHtml('Messages') ?></span></label>
                    <div class="control">
                        <textarea name="comment" id="comment" title="<?= $block->escapeHtmlAttr('Messages') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?= $block->escapeHtml($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('comment')) ?></textarea>
                    </div>
                </div>
                <?= $block->getChildHtml('form.additional.info') ?>
            </div>
            <div class="action-button">
                <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" title="<?= $block->escapeHtmlAttr('Submit') ?>"><span><?= $block->escapeHtmlAttr('Submit') ?></span></button>
            </div>
        </form>
    </div>
</div>
