<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var \Magento\Wishlist\Block\Customer\Wishlist\Items $block */
$columns = $block->getColumns();
?>
<div class="page-title-wrapper">
    <h1 class="page-title">
        <span class="base" data-ui-id="page-title-wrapper"><?php echo __('My Wish List');?></span> 
    </h1>
</div>
<div class="product-item-list row m-0">
    <?php if (count($block->getItems())) : ?>
        <?php foreach ($block->getItems() as $item) : ?>
            <div data-row="product-item" class="product-item col-sm-4" id="item_<?= $block->escapeHtmlAttr($item->getId()) ?>">
                <div data-container="product-grid">
                    <?php foreach ($columns as $column) : ?>
                        <?= $column->setItem($item)->toHtml();?>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endforeach; ?>
    <?php else : ?>
        <div class="message info empty">
            <span><?= $block->escapeHtml(__('This Wish List has no Items')) ?></span>
        </div>
    <?php endif; ?>
</div>

<?php foreach ($columns as $column) : ?>
    <?= $column->getAdditionalHtml() ?>
<?php endforeach; ?>
