
    <div class="page-wrapper">
        <div class="card-content">
            <div class="card-image" style="background-image: url('/pub/media/<?= $block->getData('image') ?>')"></div>
            <div class="card-text">
                <div class="container">
                    <h3 class="font-bold color-white text-body-40 text-body-lg-34 mb-5"><?php if ($block->getData('body_text')) { echo html_entity_decode($block->getData('body_text'));} ?></h3>
                    <div class="detail color-white text-body-18"><?php if ($block->getData('text2')) { echo html_entity_decode($block->getData('text2')); } ?></div>
                </div>
            </div>
        </div>
    </div>
