<div class="page-subpage-content mt-4 mb-5">
    <div class="page-wrapper">
        <div class="background-white">
            <div class="page-title border-none">
                <div class="container">
                    <div class="row">
                        <div class="col-md-5 mb-4">
                            <h1>
                                <?php if ($block->getData('title')) :
                                    echo $block->getData('title');
                                endif; ?>
                            </h1>
                        </div>
                        <div class="col-md-6">
                            <p>
                                <?php if ($block->getData('detail')) :
                                    echo html_entity_decode($block->getData('detail'));
                                endif; ?>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="page-content pt-0">
                <div class="container">
                    <div class="card-banner"><img class="w-100" src="/pub/media/<?= $block->getData('image') ?>" alt=""></div>
                    <div class="card-content-toggle">
                        <?php 
                        echo $this->getLayout()
                            ->createBlock('Magento\Cms\Block\Block')
                            ->setBlockId('faq-list')
                            ->toHtml();
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>