
<div class="card-item pb-5">
    <div class="card-image"><img src="/pub/media/<?= $block->getData('image') ?>" alt=""></div>
    <div class="card-text">
        <h3 class="font-medium text-body-14 color-black mb-3"><?php if ($block->getData('body_text')) : ?><?= $block->getData('body_text') ?><?php endif; ?></h3>
        <div class="detail text-body-12"><?php if ($block->getData('body_text2')) : ?><?= $block->getData('body_text2') ?><?php endif; ?></div>
    </div>
</div>
<style>
    .text-body-12{
        font-size:1.3rem;
    }
    @media (min-width: 768px){
        .page-footer .card-request-quotation .card-link img.footer-icon {
            left: 113px;
        }
    }
    @media (max-width: 467px) and (min-width: 368px){
        .page-footer .card-request-quotation .card-link img.footer-icon {
            top: 10px;
        }
    }
</style>