    <div class="card-quote-text"><?php if ($block->getData('text1')) { echo $block->getData('text1'); } ?></div>
    <div class="card-quote-link"><a class="contact-form-modal-button" href="#" data-mage-init='{&quot;contact-form-modal&quot;: {&quot;target&quot;: &quot;#modal-contact-form&quot;}}'> <span class="text"><?php
                            if ($block->getData('text2')) {
                            echo $block->getData('text2');
                        }
                        ?></span> </a></div>
