
    <div class="page-wrapper">
        <div class="card-content background-navy-3">
            <div class="container">
                <div class="row">
                    <div class="col-lg-5 card-image px-0"><img src="/pub/media/<?= $block->getData('image') ?>" alt=""></div>
                    <div class="col-lg-6 card-text d-flex align-items-center">
                        <div class="max-width-350 m-auto">
                            <h3 class="font-medium text-body-14 color-black mb-4"><?php if ($block->getData('title')) { echo $block->getData('title'); } ?></h3>
                            <h1 class="font-bold color-navy text-body-18 text-uppercase mb-4"><?php if ($block->getData('sub_title')) { echo $block->getData('sub_title'); } ?></h1>
                            <div class="detail"><?php if ($block->getData('body_text')) { echo html_entity_decode($block->getData('body_text')); } ?></div>
                            <div class="card-link card-link-plus-unbox"><a href="<?php echo $this->getUrl($block->getData('lern_more')); ?>"><?= __('LEARN MORE') ?></a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
