<?php //$data = $block->filterParameters(); ?> 
<?php //print_r($data); ?>

<div class="simple-content">
    <?php if ($block->getData('image')) : ?>
        <div class="card-image">
            <img  src="/pub/media/<?= $block->getData('image') ?>" alt="" />
        </div>
    <?php endif; ?>
    <div class="card-text">
        <?php if ($block->getData('title')) : ?><h2 class="color-gold"><?= $block->getData('title') ?></h2><?php endif; ?>
        <?php if ($block->getData('body_text')) : ?><?= html_entity_decode($block->getData('body_text')) ?> <?php endif; ?>
        <?php if ($block->getData('link')) : ?><div class="link"><a href="<?= $block->getData('link') ?>">
                    <?php echo ($block->getData('linktext')) ? $block->getData('linktext') : 'Read More'; ?></a></div><?php endif; ?>
    </div>
</div> 