<div class="content-static content-normal-content">
    <div class="container">
        <div>
            <?php if ($block->getData('image')) : ?>
                <div class="banner mb-4"><img class="w-100" src="/pub/media/<?= $block->getData('image') ?>" alt=""></div>
            <?php endif; ?>
            <?php if ($block->getData('title')) : ?><h2><?= $block->getData('title') ?></h2><?php endif; ?>

            <?php if ($block->getData('subtitle')) : ?><h3><?= $block->getData('subtitle') ?></h3><?php endif; ?>

            <?php if ($block->getData('body_text')) : ?>

                <?= html_entity_decode($block->getData('body_text')) ?>
            <?php endif; ?>
        </div>
    </div>
</div>