
                        <div class="card-content-row">
                            <div class="row">
                                <div class="col-md-4 offset-md-1">
                                    <div class="card-title font-bold text-body-40 text-body-lg-34 text-body-sm-24 color-body-40"><?php if ($block->getData('title')) : ?><?= $block->getData('title') ?><?php endif; ?></div>
                                </div>
                                <div class="col-md-6 card-content">
                                    <?php echo html_entity_decode($block->getData('detail')); ?>
                                </div>
                            </div>
                        </div>




