<?php //$data = $block->filterParameters(); ?> 
<?php //print_r($data); ?>

<div class="subpage-banner position-relative"> 
    <?php if ($block->getData('image')) : ?>
        <div class="card-image">
            <img class="w-100" src="/pub/media/<?= $block->getData('image') ?>" alt="" />
        </div>
    <?php endif; ?>
    <div class="card-text"> 
        <div class="container">
        <?php if ($block->getData('title')) : ?><h1 class="color-white text-body-46 font-medium m-0"><?= $block->getData('title') ?></h1><?php endif; ?>
        <?php /*if ($block->getData('body_text')) : ?><?= html_entity_decode($block->getData('body_text')) ?> <?php endif; ?>
        <?php if ($block->getData('link')) : ?><div class="link"><a href="<?= $block->getData('link') ?>"><?php echo ($block->getData('linktext')) ? $block->getData('linktext') : 'Read More'; ?></a></div><?php endif; */?>
        </div>
    </div>
</div>     