<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$specificInfo = $block->getInstructions();
$title = $block->escapeHtml($block->getMethod()->getTitle());
?>
<dl class="payment-method">
    <dt class="title"><?= /* @noEscape */ $title ?></dt>
    <?php if ($specificInfo) : ?>
        <dd class="content">
            <?= /* @noEscape */ nl2br($block->escapeHtml($specificInfo)) ?>
        </dd>
    <?php endif;?>
</dl>
<?= $block->getChildHtml() ?>