<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */
$_item = $block->getItem();
$product = $_item->getProduct();
if($product->getTypeId() == 'configurable') {
    $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();   
    $configurable = $objectManager->get('\Magento\ConfigurableProduct\Model\Product\Type\Configurable');
    $superAttribute = array();
    foreach ($block->getItemOptions() as $option) {
        $superAttribute[$option['option_id']] = $option['option_value'];
    }
    $product = $configurable->getProductByAttributes($superAttribute ,$product);
}
?>
<tr id="order-item-row-<?= (int) $_item->getId() ?>" class="item-info">
    <td class="col detail" data-th="<?= $block->escapeHtmlAttr(__('Product Name')) ?>">
        <div class="product-item-details">
            <strong class="product-item-name">
                <a href="<?= $block->escapeHtml($_item->getProduct()->getProductUrl()) ?>"><?= $block->escapeHtml($product->getName()) ?></a>
            </strong>
            <?php if ($_options = $block->getItemOptions()) : ?>
                <dl class="product options list">
                    <?php foreach ($_options as $_option) : ?>
                        <span><?= $block->escapeHtml($_option['label']) ?> = </span>
                        <?php if (!$block->getPrintStatus()) : ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <span>
                                <?php if (isset($_formatedOptionValue['full_view'])) : ?>
                                    <?= $block->escapeHtml($_formatedOptionValue['full_view'], ['a']) ?>
                                <?php else : ?>
                                    <?=$block->escapeHtml($_formatedOptionValue['value'], ['a']) ?>
                                <?php endif; ?>
                            </span>
                        <?php else : ?>
                            <span>
                                <?= /* @noEscape */ nl2br($block->escapeHtml($_option['print_value'] ?? $_option['value'])) ?>
                            </span>
                        <?php endif; ?><br>
                    <?php endforeach; ?>
                </dl>   
            <?php endif; ?> 
            <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addtInfoBlock) : ?>
                <?= $addtInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif; ?>
            <?= $block->escapeHtml($_item->getDescription()) ?>                                          
        </div>
    </td>
    <td class="col sku" data-th="<?= $block->escapeHtmlAttr(__('Part Number')) ?>"><?= $block->escapeHtml($product->getData('part_number')); ?></td>
    <td class="col price" data-th="<?= $block->escapeHtmlAttr(__('Price')) ?>">
        <?= $block->getItemPriceHtml() ?>
    </td>
    <td class="col qty" data-th="<?= $block->escapeHtmlAttr(__('Qty')) ?>">
        <ul class="items-qty">
        <?php if ($block->getItem()->getQtyOrdered() > 0) : ?>
            <li class="item">
                <span class="title"><?= $block->escapeHtml(__('Ordered')) ?></span>
                <span class="content"><?= (float) $block->getItem()->getQtyOrdered() ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyShipped() > 0) : ?>
            <li class="item">
                <span class="title"><?= $block->escapeHtml(__('Shipped')) ?></span>
                <span class="content"><?= (float) $block->getItem()->getQtyShipped() ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyCanceled() > 0) : ?>
            <li class="item">
                <span class="title"><?= $block->escapeHtml(__('Canceled')) ?></span>
                <span class="content"><?= (float) $block->getItem()->getQtyCanceled() ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyRefunded() > 0) : ?>
            <li class="item">
                <span class="title"><?= $block->escapeHtml(__('Refunded')) ?></span>
                <span class="content"><?= (float) $block->getItem()->getQtyRefunded() ?></span>
            </li>
        <?php endif; ?>
        </ul>
    </td>
    <td class="col subtotal" data-th="<?= $block->escapeHtmlAttr(__('Subtotal')) ?>">
        <?= $block->getItemRowTotalHtml() ?>
    </td>
</tr>
