<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Top menu for store
 *
 * @var $block \Kos\CatalogExtend\Block\Category\Tree
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit)
?>

<nav class="card-category-nav-list card-category-list pt-5 pt-sm-0" data-action="navigation">
    <div class="card-title font-bold text-body-18 color-black text-sm-left text-center">Categories</div>
    <div class="card-list">
        <div class="cat-scroll cat-nav-content">
<!--        <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>-->
            <ul class="level-root submenu">
                <?= /* @noEscape */ $_menuHtml?>
                <?= $block->getChildHtml() ?>
            </ul>
        </div>
    </div>
    <div class="card-all">
        <a href="#">
            <span><i class="icomoon-screw text-body-26 color-orange"></i></span>
            <span class="text small-title">All Categories</span>
        </a>
    </div>
</nav>
