<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>

<?php if ($block->getCanViewOrder() && $block->getCanPrintOrder()) :?>
    <button type="button" onclick="window.open('<?= $block->escapeUrl($block->getPrintUrl()) ?>', '_blank');"><span><?= $block->escapeHtml(__('Print receipt')) ?></span></button>
<?php endif;?>
