<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Store\Block\Switcher $block */
?>
<?php if (count($block->getStores())>1) : ?>
<div class="head-switching head-store-view">
    <div class="card-switching">
         <div class="cs-select" tabindex="0">
            <span class="view-icon cs-placeholder view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?>"><?= $block->escapeHtml($block->getStoreName()) ?></span>
            <div class="cs-options">
                <ul>
                    <?php foreach ($block->getStores() as $_lang) : ?>
                        <li>
                            <a href="<?= $block->escapeUrl($block->getViewModel()->getTargetStoreRedirectUrl($_lang)) ?>">
                                <span class="view-icon view-<?= $block->escapeHtml($_lang->getCode()) ?>"> <?= $block->escapeHtml($_lang->getName()) ?></span>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>