<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
?>
<div class="image-top" style="background-image:url(<?php echo $this->getViewFileUrl('images/banner/nut2.png'); ?>);"></div>
<h1 class="text-center"><img src="<?php echo $this->getViewFileUrl('images/error.svg'); ?>" width="100" /></h1>
<h1 class="text-center"><?php echo __('404 Page not Found'); ?></h1>
<p class="text-center"><?php echo __('We can\'t find the page you\'re looking for.'); ?></p>
<div class="action-button">
    <button type="button" onclick="window.location='<?=$this->getUrl()?>'"><span><?= $block->escapeHtml(__('Visit Homepage')) ?></span></button>
</div>
<div class="image-bottom" style="background-image:url(<?php echo $this->getViewFileUrl('images/banner/nut1.png'); ?>)"></div>
